#!/usr/bin/env bash
# SBOM generation — M0 STUB.
#
# M0 emits a dependency manifest via `cargo tree` so the supply chain is captured from
# day one. A later milestone replaces this with a CycloneDX SBOM
# (`cargo cyclonedx --format json`) wired into the release pipeline.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${1:-sbom-stub.txt}"
{
  echo "# Secure Vault dependency manifest (SBOM stub)"
  echo "# Generated by scripts/sbom.sh — replace with CycloneDX before release."
  echo
  cargo tree --workspace --edges normal --no-dedupe
} > "$OUT"
echo "wrote $OUT"
